package com.tab;

import com.UserInterface;
import com.connectdatabase.DataBaseConnect;
import com.objects.Seat;
import com.objects.User;
import java.awt.Color;
import java.awt.Component;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;

public class TabBookSeat extends javax.swing.JPanel {

    /**
     * Creates new form TabBookSeat
     *
     */
    public ArrayList<String> gheDuocDat = new ArrayList<>();
    private int soLuong = 0;
    private final int donGia = 40000;
    private UserInterface userInterface;
    private User userCucBo;
    private final java.awt.Color HOVER_COLOR = new java.awt.Color(0, 163, 55);
    private final java.awt.Color DEFAULT_COLOR = new java.awt.Color(0, 204, 68);

    public TabBookSeat(UserInterface userInterface, User user) {
        initComponents();    
        addSeatButtonListeners();
        setMatchIDTojcbxSelectMatch();
        initStatus(user);
        this.userInterface = userInterface;
        this.userCucBo = user;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeats = new javax.swing.JPanel();
        jButtonGheA01 = new javax.swing.JButton();
        jButtonGheA02 = new javax.swing.JButton();
        jButtonGheA03 = new javax.swing.JButton();
        jButtonGheA04 = new javax.swing.JButton();
        jButtonGheA05 = new javax.swing.JButton();
        jButtonGheA06 = new javax.swing.JButton();
        jButtonGheA07 = new javax.swing.JButton();
        jButtonGheA08 = new javax.swing.JButton();
        jButtonGheA09 = new javax.swing.JButton();
        jButtonGheA10 = new javax.swing.JButton();
        jButtonGheB01 = new javax.swing.JButton();
        jButtonGheB02 = new javax.swing.JButton();
        jButtonGheB03 = new javax.swing.JButton();
        jButtonGheB04 = new javax.swing.JButton();
        jButtonGheB05 = new javax.swing.JButton();
        jButtonGheB06 = new javax.swing.JButton();
        jButtonGheB07 = new javax.swing.JButton();
        jButtonGheB08 = new javax.swing.JButton();
        jButtonGheB09 = new javax.swing.JButton();
        jButtonGheB10 = new javax.swing.JButton();
        jButtonGheC01 = new javax.swing.JButton();
        jButtonGheC02 = new javax.swing.JButton();
        jButtonGheC03 = new javax.swing.JButton();
        jButtonGheC04 = new javax.swing.JButton();
        jButtonGheC05 = new javax.swing.JButton();
        jButtonGheC06 = new javax.swing.JButton();
        jButtonGheC07 = new javax.swing.JButton();
        jButtonGheC08 = new javax.swing.JButton();
        jButtonGheC09 = new javax.swing.JButton();
        jButtonGheC10 = new javax.swing.JButton();
        jButtonGheD01 = new javax.swing.JButton();
        jButtonGheD02 = new javax.swing.JButton();
        jButtonGheD03 = new javax.swing.JButton();
        jButtonGheD04 = new javax.swing.JButton();
        jButtonGheD05 = new javax.swing.JButton();
        jButtonGheD06 = new javax.swing.JButton();
        jButtonGheD07 = new javax.swing.JButton();
        jButtonGheD08 = new javax.swing.JButton();
        jButtonGheD09 = new javax.swing.JButton();
        jButtonGheD10 = new javax.swing.JButton();
        jButtonGheE01 = new javax.swing.JButton();
        jButtonGheE02 = new javax.swing.JButton();
        jButtonGheE03 = new javax.swing.JButton();
        jButtonGheE04 = new javax.swing.JButton();
        jButtonGheE05 = new javax.swing.JButton();
        jButtonGheE06 = new javax.swing.JButton();
        jButtonGheE07 = new javax.swing.JButton();
        jButtonGheE08 = new javax.swing.JButton();
        jButtonGheE09 = new javax.swing.JButton();
        jButtonGheE10 = new javax.swing.JButton();
        jButtonGheF01 = new javax.swing.JButton();
        jButtonGheF02 = new javax.swing.JButton();
        jButtonGheF03 = new javax.swing.JButton();
        jButtonGheF04 = new javax.swing.JButton();
        jButtonGheF05 = new javax.swing.JButton();
        jButtonGheF06 = new javax.swing.JButton();
        jButtonGheF07 = new javax.swing.JButton();
        jButtonGheF08 = new javax.swing.JButton();
        jButtonGheF09 = new javax.swing.JButton();
        jButtonGheF10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUserID = new javax.swing.JTextField();
        jTextFieldFullName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButtonConfrimSeatAndChangeTabOrderAndPayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSeat = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jComboxSelectMatch = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(248, 248, 248));
        setPreferredSize(new java.awt.Dimension(900, 520));

        jPanelSeats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSeats.setLayout(new java.awt.GridLayout(6, 10));

        jButtonGheA01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA01.setText("A01");
        jButtonGheA01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA01);

        jButtonGheA02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA02.setText("A02");
        jButtonGheA02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA02);

        jButtonGheA03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA03.setText("A03");
        jButtonGheA03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA03);

        jButtonGheA04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA04.setText("A04");
        jButtonGheA04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA04);

        jButtonGheA05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA05.setText("A05");
        jButtonGheA05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA05);

        jButtonGheA06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA06.setText("A06");
        jButtonGheA06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA06);

        jButtonGheA07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA07.setText("A07");
        jButtonGheA07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA07);

        jButtonGheA08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA08.setText("A08");
        jButtonGheA08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA08);

        jButtonGheA09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA09.setText("A09");
        jButtonGheA09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA09);

        jButtonGheA10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheA10.setText("A10");
        jButtonGheA10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheA10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheA10);

        jButtonGheB01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB01.setText("B01");
        jButtonGheB01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB01);

        jButtonGheB02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB02.setText("B02");
        jButtonGheB02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB02);

        jButtonGheB03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB03.setText("B03");
        jButtonGheB03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB03);

        jButtonGheB04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB04.setText("B04");
        jButtonGheB04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB04);

        jButtonGheB05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB05.setText("B05");
        jButtonGheB05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB05);

        jButtonGheB06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB06.setText("B06");
        jButtonGheB06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB06);

        jButtonGheB07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB07.setText("B07");
        jButtonGheB07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB07);

        jButtonGheB08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB08.setText("B08");
        jButtonGheB08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB08);

        jButtonGheB09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB09.setText("B09");
        jButtonGheB09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB09);

        jButtonGheB10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheB10.setText("B10");
        jButtonGheB10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheB10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheB10);

        jButtonGheC01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC01.setText("C01");
        jButtonGheC01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC01);

        jButtonGheC02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC02.setText("C02");
        jButtonGheC02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC02);

        jButtonGheC03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC03.setText("C03");
        jButtonGheC03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC03);

        jButtonGheC04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC04.setText("C04");
        jButtonGheC04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC04);

        jButtonGheC05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC05.setText("C05");
        jButtonGheC05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC05);

        jButtonGheC06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC06.setText("C06");
        jButtonGheC06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC06);

        jButtonGheC07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC07.setText("C07");
        jButtonGheC07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC07);

        jButtonGheC08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC08.setText("C08");
        jButtonGheC08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC08);

        jButtonGheC09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC09.setText("C09");
        jButtonGheC09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC09);

        jButtonGheC10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheC10.setText("C10");
        jButtonGheC10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheC10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheC10);

        jButtonGheD01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD01.setText("D01");
        jButtonGheD01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD01);

        jButtonGheD02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD02.setText("D02");
        jButtonGheD02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD02);

        jButtonGheD03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD03.setText("D03");
        jButtonGheD03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD03);

        jButtonGheD04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD04.setText("D04");
        jButtonGheD04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD04);

        jButtonGheD05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD05.setText("D05");
        jButtonGheD05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD05);

        jButtonGheD06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD06.setText("D06");
        jButtonGheD06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD06);

        jButtonGheD07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD07.setText("D07");
        jButtonGheD07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD07);

        jButtonGheD08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD08.setText("D08");
        jButtonGheD08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD08);

        jButtonGheD09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD09.setText("D09");
        jButtonGheD09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD09);

        jButtonGheD10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheD10.setText("D10");
        jButtonGheD10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheD10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheD10);

        jButtonGheE01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE01.setText("E01");
        jButtonGheE01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE01);

        jButtonGheE02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE02.setText("E02");
        jButtonGheE02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE02);

        jButtonGheE03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE03.setText("E03");
        jButtonGheE03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE03);

        jButtonGheE04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE04.setText("E04");
        jButtonGheE04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE04);

        jButtonGheE05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE05.setText("E05");
        jButtonGheE05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE05);

        jButtonGheE06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE06.setText("E06");
        jButtonGheE06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE06);

        jButtonGheE07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE07.setText("E07");
        jButtonGheE07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE07);

        jButtonGheE08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE08.setText("E08");
        jButtonGheE08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE08);

        jButtonGheE09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE09.setText("E09");
        jButtonGheE09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE09);

        jButtonGheE10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheE10.setText("E10");
        jButtonGheE10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheE10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheE10);

        jButtonGheF01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF01.setText("F01");
        jButtonGheF01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF01.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF01);

        jButtonGheF02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF02.setText("F02");
        jButtonGheF02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF02.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF02);

        jButtonGheF03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF03.setText("F03");
        jButtonGheF03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF03.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF03);

        jButtonGheF04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF04.setText("F04");
        jButtonGheF04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF04.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF04);

        jButtonGheF05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF05.setText("F05");
        jButtonGheF05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF05.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF05);

        jButtonGheF06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF06.setText("F06");
        jButtonGheF06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF06.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF06);

        jButtonGheF07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF07.setText("F07");
        jButtonGheF07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF07.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF07);

        jButtonGheF08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF08.setText("F08");
        jButtonGheF08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF08.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF08);

        jButtonGheF09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF09.setText("F09");
        jButtonGheF09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF09.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF09);

        jButtonGheF10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButtonGheF10.setText("F10");
        jButtonGheF10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGheF10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanelSeats.add(jButtonGheF10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("User ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PassWord:");

        jTextFieldUserID.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldUserID.setText("10002321");
        jTextFieldUserID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jTextFieldFullName.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldFullName.setText("Huỳnh Hoàng Khoa");
        jTextFieldFullName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jTextFieldEmail.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldEmail.setText("N23DCCN166");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jTextFieldPhone.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldPhone.setText("0375065207");
        jTextFieldPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jPasswordFieldPass.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordFieldPass.setText("jPasswordField1");
        jPasswordFieldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jButtonConfrimSeatAndChangeTabOrderAndPayment.setBackground(new java.awt.Color(46, 204, 113));
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setText("Confirmation & Payment");
        jButtonConfrimSeatAndChangeTabOrderAndPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseExited(evt);
            }
        });
        jButtonConfrimSeatAndChangeTabOrderAndPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfrimSeatAndChangeTabOrderAndPaymentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Seat:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Amount:");

        jTextFieldSeat.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldSeat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        jTextFieldAmount.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConfrimSeatAndChangeTabOrderAndPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldFullName)
                            .addComponent(jTextFieldUserID)
                            .addComponent(jPasswordFieldPass)
                            .addComponent(jTextFieldSeat)
                            .addComponent(jTextFieldAmount))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButtonConfrimSeatAndChangeTabOrderAndPayment)
                .addContainerGap())
        );

        jComboxSelectMatch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboxSelectMatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Match1 (VIE - THA)", "Match2 (ENG - URU)", "Match3 (BRA - GER)", "Match4 (JPN - POR)" }));
        jComboxSelectMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboxSelectMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboxSelectMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboxSelectMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initStatus(User user) {
        jTextFieldFullName.setEditable(false);
        jTextFieldUserID.setEditable(false);
        jTextFieldEmail.setEditable(false);
        jTextFieldAmount.setEditable(false);
        jTextFieldPhone.setEditable(false);
        jTextFieldSeat.setEditable(false);
        jPasswordFieldPass.setEditable(false);
        jTextFieldFullName.setText(user.getFull_name());
        jTextFieldUserID.setText(user.getUser_id());
        jTextFieldEmail.setText(user.getEmail());
        jTextFieldPhone.setText(user.getPhone());
        jPasswordFieldPass.setText(user.getPass());
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setEnabled(false);
        for (char hang = 'A'; hang <= 'F'; hang++) {
            for (int cot = 1; cot <= 10; cot++) {
                String tenGhe = String.format("jButtonGhe%c%02d", hang, cot);
                try {
                    Field field = getClass().getDeclaredField(tenGhe);
                    field.setAccessible(true);
                    JButton ghe = (JButton) field.get(this);
                    ghe.setEnabled(false);
                } catch (IllegalAccessException | IllegalArgumentException | NoSuchFieldException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    private void setMatchIDTojcbxSelectMatch() {
        ArrayList<String> data = DataBaseConnect.getMatchID();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        jComboxSelectMatch.setModel(model);

        if (!data.isEmpty()) {
            jComboxSelectMatch.setSelectedIndex(0);
            
        }
    }

    public boolean test() {
        ArrayList<String> data = DataBaseConnect.getMatchID();
        return data.isEmpty();
    }

    private void jComboxSelectMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboxSelectMatchActionPerformed
        String matchID = jComboxSelectMatch.getSelectedItem().toString();
        try {
            ArrayList<Vector> arr = DataBaseConnect.getDataSeatsAccordingToTheMatch(matchID);
            setStatusGheFollowComboBox(arr);
        } catch (SQLException | ClassNotFoundException ex) {
            System.getLogger(TabBookSeat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_jComboxSelectMatchActionPerformed

    private void setStatusGheFollowComboBox(ArrayList<Vector> arr) {
        for (Vector row : arr) {
            String seatId = row.get(2).toString().trim();
            int statusInt = (Integer) row.get(3);
            boolean status = (statusInt == 1);

            switch (seatId) {
                case "A01" ->
                    jButtonGheA01.setEnabled(!status);
                case "A02" ->
                    jButtonGheA02.setEnabled(!status);
                case "A03" ->
                    jButtonGheA03.setEnabled(!status);
                case "A04" ->
                    jButtonGheA04.setEnabled(!status);
                case "A05" ->
                    jButtonGheA05.setEnabled(!status);
                case "A06" ->
                    jButtonGheA06.setEnabled(!status);
                case "A07" ->
                    jButtonGheA07.setEnabled(!status);
                case "A08" ->
                    jButtonGheA08.setEnabled(!status);
                case "A09" ->
                    jButtonGheA09.setEnabled(!status);
                case "A10" ->
                    jButtonGheA10.setEnabled(!status);
                case "B01" ->
                    jButtonGheB01.setEnabled(!status);
                case "B02" ->
                    jButtonGheB02.setEnabled(!status);
                case "B03" ->
                    jButtonGheB03.setEnabled(!status);
                case "B04" ->
                    jButtonGheB04.setEnabled(!status);
                case "B05" ->
                    jButtonGheB05.setEnabled(!status);
                case "B06" ->
                    jButtonGheB06.setEnabled(!status);
                case "B07" ->
                    jButtonGheB07.setEnabled(!status);
                case "B08" ->
                    jButtonGheB08.setEnabled(!status);
                case "B09" ->
                    jButtonGheB09.setEnabled(!status);
                case "B10" ->
                    jButtonGheB10.setEnabled(!status);
                case "C01" ->
                    jButtonGheC01.setEnabled(!status);
                case "C02" ->
                    jButtonGheC02.setEnabled(!status);
                case "C03" ->
                    jButtonGheC03.setEnabled(!status);
                case "C04" ->
                    jButtonGheC04.setEnabled(!status);
                case "C05" ->
                    jButtonGheC05.setEnabled(!status);
                case "C06" ->
                    jButtonGheC06.setEnabled(!status);
                case "C07" ->
                    jButtonGheC07.setEnabled(!status);
                case "C08" ->
                    jButtonGheC08.setEnabled(!status);
                case "C09" ->
                    jButtonGheC09.setEnabled(!status);
                case "C10" ->
                    jButtonGheC10.setEnabled(!status);
                case "D01" ->
                    jButtonGheD01.setEnabled(!status);
                case "D02" ->
                    jButtonGheD02.setEnabled(!status);
                case "D03" ->
                    jButtonGheD03.setEnabled(!status);
                case "D04" ->
                    jButtonGheD04.setEnabled(!status);
                case "D05" ->
                    jButtonGheD05.setEnabled(!status);
                case "D06" ->
                    jButtonGheD06.setEnabled(!status);
                case "D07" ->
                    jButtonGheD07.setEnabled(!status);
                case "D08" ->
                    jButtonGheD08.setEnabled(!status);
                case "D09" ->
                    jButtonGheD09.setEnabled(!status);
                case "D10" ->
                    jButtonGheD10.setEnabled(!status);
                case "E01" ->
                    jButtonGheE01.setEnabled(!status);
                case "E02" ->
                    jButtonGheE02.setEnabled(!status);
                case "E03" ->
                    jButtonGheE03.setEnabled(!status);
                case "E04" ->
                    jButtonGheE04.setEnabled(!status);
                case "E05" ->
                    jButtonGheE05.setEnabled(!status);
                case "E06" ->
                    jButtonGheE06.setEnabled(!status);
                case "E07" ->
                    jButtonGheE07.setEnabled(!status);
                case "E08" ->
                    jButtonGheE08.setEnabled(!status);
                case "E09" ->
                    jButtonGheE09.setEnabled(!status);
                case "E10" ->
                    jButtonGheE10.setEnabled(!status);
                case "F01" ->
                    jButtonGheF01.setEnabled(!status);
                case "F02" ->
                    jButtonGheF02.setEnabled(!status);
                case "F03" ->
                    jButtonGheF03.setEnabled(!status);
                case "F04" ->
                    jButtonGheF04.setEnabled(!status);
                case "F05" ->
                    jButtonGheF05.setEnabled(!status);
                case "F06" ->
                    jButtonGheF06.setEnabled(!status);
                case "F07" ->
                    jButtonGheF07.setEnabled(!status);
                case "F08" ->
                    jButtonGheF08.setEnabled(!status);
                case "F09" ->
                    jButtonGheF09.setEnabled(!status);
                case "F10" ->
                    jButtonGheF10.setEnabled(!status);
                default -> {
                }
            }
        }
    }

    private void setAmountAndSetAndGheDuocDat(String ghe) {
        gheDuocDat.add(ghe);
        String currentText = jTextFieldSeat.getText();
        currentText = currentText + " " + ghe;
        jTextFieldSeat.setText(currentText);
        soLuong++;
        jTextFieldAmount.setText("" + soLuong * donGia);
    }

    private void addSeatButtonListeners() {
        for (Component c : jPanelSeats.getComponents()) {
            if (c instanceof JButton) {
                JButton seatButton = (JButton) c;
                seatButton.addActionListener(evt -> handleSeatClick(seatButton));
            }
        }
    }

    private void handleSeatClick(JButton seatButton) {
        seatButton.setEnabled(false);
        seatButton.setBackground(Color.RED);
        seatButton.setOpaque(true);
        seatButton.setContentAreaFilled(true);
        seatButton.setBorderPainted(true);
        jComboxSelectMatch.setEnabled(false);
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setEnabled(true);

        String seatCode = seatButton.getText();
        setAmountAndSetAndGheDuocDat(seatCode);
    }


    private void jButtonConfrimSeatAndChangeTabOrderAndPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentActionPerformed
        try {
            ArrayList<Seat> listSeat = new ArrayList<>();
            String matchID = (String) jComboxSelectMatch.getSelectedItem();
            String stadiumID = DataBaseConnect.selectStadiumIDbyMatchID(matchID);
            int amount = Integer.parseInt(jTextFieldAmount.getText());
            for (String item : gheDuocDat) {
                Seat s = new Seat(matchID, stadiumID, item, true);
                listSeat.add(s);
                DataBaseConnect.updateSeat(s);
            }
            userInterface.deleteTab();
            userInterface.btnBookTicketInTabBookTicKet(userCucBo, listSeat, amount);

        } catch (SQLException | ClassNotFoundException ex) {
            System.getLogger(TabBookSeat.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentActionPerformed

    private void jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseEntered
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setBackground(HOVER_COLOR);
    }//GEN-LAST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseEntered

    private void jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseExited
        jButtonConfrimSeatAndChangeTabOrderAndPayment.setBackground(DEFAULT_COLOR);
    }//GEN-LAST:event_jButtonConfrimSeatAndChangeTabOrderAndPaymentMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfrimSeatAndChangeTabOrderAndPayment;
    private javax.swing.JButton jButtonGheA01;
    private javax.swing.JButton jButtonGheA02;
    private javax.swing.JButton jButtonGheA03;
    private javax.swing.JButton jButtonGheA04;
    private javax.swing.JButton jButtonGheA05;
    private javax.swing.JButton jButtonGheA06;
    private javax.swing.JButton jButtonGheA07;
    private javax.swing.JButton jButtonGheA08;
    private javax.swing.JButton jButtonGheA09;
    private javax.swing.JButton jButtonGheA10;
    private javax.swing.JButton jButtonGheB01;
    private javax.swing.JButton jButtonGheB02;
    private javax.swing.JButton jButtonGheB03;
    private javax.swing.JButton jButtonGheB04;
    private javax.swing.JButton jButtonGheB05;
    private javax.swing.JButton jButtonGheB06;
    private javax.swing.JButton jButtonGheB07;
    private javax.swing.JButton jButtonGheB08;
    private javax.swing.JButton jButtonGheB09;
    private javax.swing.JButton jButtonGheB10;
    private javax.swing.JButton jButtonGheC01;
    private javax.swing.JButton jButtonGheC02;
    private javax.swing.JButton jButtonGheC03;
    private javax.swing.JButton jButtonGheC04;
    private javax.swing.JButton jButtonGheC05;
    private javax.swing.JButton jButtonGheC06;
    private javax.swing.JButton jButtonGheC07;
    private javax.swing.JButton jButtonGheC08;
    private javax.swing.JButton jButtonGheC09;
    private javax.swing.JButton jButtonGheC10;
    private javax.swing.JButton jButtonGheD01;
    private javax.swing.JButton jButtonGheD02;
    private javax.swing.JButton jButtonGheD03;
    private javax.swing.JButton jButtonGheD04;
    private javax.swing.JButton jButtonGheD05;
    private javax.swing.JButton jButtonGheD06;
    private javax.swing.JButton jButtonGheD07;
    private javax.swing.JButton jButtonGheD08;
    private javax.swing.JButton jButtonGheD09;
    private javax.swing.JButton jButtonGheD10;
    private javax.swing.JButton jButtonGheE01;
    private javax.swing.JButton jButtonGheE02;
    private javax.swing.JButton jButtonGheE03;
    private javax.swing.JButton jButtonGheE04;
    private javax.swing.JButton jButtonGheE05;
    private javax.swing.JButton jButtonGheE06;
    private javax.swing.JButton jButtonGheE07;
    private javax.swing.JButton jButtonGheE08;
    private javax.swing.JButton jButtonGheE09;
    private javax.swing.JButton jButtonGheE10;
    private javax.swing.JButton jButtonGheF01;
    private javax.swing.JButton jButtonGheF02;
    private javax.swing.JButton jButtonGheF03;
    private javax.swing.JButton jButtonGheF04;
    private javax.swing.JButton jButtonGheF05;
    private javax.swing.JButton jButtonGheF06;
    private javax.swing.JButton jButtonGheF07;
    private javax.swing.JButton jButtonGheF08;
    private javax.swing.JButton jButtonGheF09;
    private javax.swing.JButton jButtonGheF10;
    private javax.swing.JComboBox<String> jComboxSelectMatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSeats;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldSeat;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
