package com.tab;

import com.Main;
import com.connectdatabase.DataBaseConnect;
import com.objects.Match;
import com.objects.Stadium;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TabCreateNew extends javax.swing.JPanel {
    private Main userInterface;

    /**
     * Creates new form TabShowTicket1
     *
     * @param userInterface
     */
    
    public TabCreateNew(Main userInterface) {
        initComponents();
        this.userInterface = userInterface;
        setStatusDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSelect = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldStadiumID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNameStadium = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jButtonConfirmStadium = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAwayTeam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldHomeTeam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMatchID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMatchDate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTournament = new javax.swing.JTextField();
        jButtonConfirmMatch = new javax.swing.JButton();
        jComboBoxStadiumId = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manager48.png"))); // NOI18N
        jLabel1.setText("Create New Stadium And Match");

        jComboBoxSelect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Create New Stadium", "Create New Match" }));
        jComboBoxSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stadiums.png"))); // NOI18N
        jLabel2.setText("Stadium:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Stadium ID:");

        jTextFieldStadiumID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldStadiumID.setPreferredSize(new java.awt.Dimension(100, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Name:");

        jTextFieldNameStadium.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Location:");

        jTextFieldLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Capacity:");

        jTextFieldCapacity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCapacity.setPreferredSize(new java.awt.Dimension(100, 26));

        jButtonConfirmStadium.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirmStadium.setText("OK");
        jButtonConfirmStadium.setPreferredSize(new java.awt.Dimension(80, 27));
        jButtonConfirmStadium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmStadiumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConfirmStadium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldStadiumID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameStadium, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jTextFieldLocation)
                            .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldStadiumID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNameStadium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jButtonConfirmStadium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Home team:");

        jTextFieldAwayTeam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Stadium ID:");

        jTextFieldHomeTeam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Match ID:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matches.png"))); // NOI18N
        jLabel7.setText("Match:");

        jTextFieldMatchID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMatchID.setPreferredSize(new java.awt.Dimension(100, 26));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Away team:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Match Date: ");

        jTextFieldMatchDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tournament:");

        jTextFieldTournament.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonConfirmMatch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirmMatch.setText("OK");
        jButtonConfirmMatch.setPreferredSize(new java.awt.Dimension(80, 27));
        jButtonConfirmMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmMatchActionPerformed(evt);
            }
        });

        jComboBoxStadiumId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxStadiumId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default" }));
        jComboBoxStadiumId.setPreferredSize(new java.awt.Dimension(100, 26));

        jLabel14.setText("'2025-12-29 19:00:00'");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConfirmMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAwayTeam)
                                .addComponent(jTextFieldHomeTeam)
                                .addComponent(jComboBoxStadiumId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldTournament, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldMatchDate, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldHomeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAwayTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxStadiumId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldMatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldTournament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonConfirmMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private String createIDStadium() {
        int sl = DataBaseConnect.getCountStadium();
        String res = String.format("STD%03d", sl + 1);
        return res;
    }
    
    private String createIDMatch() {
        int sl = DataBaseConnect.getCountMatch();
        String res = String.format("M%03d", sl + 1);
        return res;
    }
    
    private void setStadiumIDTojcbxSelectStadium() {
        ArrayList<String> data = DataBaseConnect.getStadiumID();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        jComboBoxStadiumId.setModel(model);

        if (!data.isEmpty()) {
            jComboBoxStadiumId.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Không có MatchID nào!");
            setStatusDefault();
        }
    }

    private void setStatusStadium() {
        setStatusDefault();
        jTextFieldStadiumID.setEnabled(true);
        jTextFieldStadiumID.setEditable(false);
        jTextFieldStadiumID.setText(createIDStadium());
        jTextFieldNameStadium.setEnabled(true);
        jTextFieldLocation.setEnabled(true);
        jTextFieldCapacity.setEnabled(true);
        jTextFieldCapacity.setEditable(false);
        jTextFieldCapacity.setText("60");
        jButtonConfirmStadium.setEnabled(true);
    }
    
    private void setStatusMatch() {
        setStatusDefault();
        jTextFieldMatchID.setEnabled(true);
        jTextFieldMatchID.setEditable(false);
        jTextFieldMatchID.setText(createIDMatch());
        jTextFieldHomeTeam.setEnabled(true);
        jTextFieldAwayTeam.setEnabled(true);
        jComboBoxStadiumId.setEnabled(true);       
        jTextFieldMatchDate.setEnabled(true);
        jTextFieldTournament.setEnabled(true);
        jButtonConfirmMatch.setEnabled(true);
        setStadiumIDTojcbxSelectStadium();
    }
    
    private void setStatusDefault() {
        jTextFieldStadiumID.setEnabled(false);
        jTextFieldStadiumID.setText("");
        jTextFieldNameStadium.setEnabled(false);
        jTextFieldNameStadium.setText("");
        jTextFieldLocation.setEnabled(false);
        jTextFieldLocation.setText("");
        jTextFieldCapacity.setEnabled(false);
        jTextFieldCapacity.setText("");
        jButtonConfirmStadium.setEnabled(false);
        
        jTextFieldMatchID.setEnabled(false);
        jTextFieldMatchID.setText("");
        jTextFieldHomeTeam.setEnabled(false);
        jTextFieldHomeTeam.setText("");
        jTextFieldAwayTeam.setEnabled(false);
        jTextFieldAwayTeam.setText("");
        jComboBoxStadiumId.setEnabled(false);
        jTextFieldMatchDate.setEnabled(false);
        jTextFieldMatchDate.setText("");
        jTextFieldTournament.setEnabled(false);
        jTextFieldTournament.setText("");
        jButtonConfirmMatch.setEnabled(false);
    }
    
    private void jComboBoxSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectActionPerformed
        String sel = (String) jComboBoxSelect.getSelectedItem();
        switch (sel) {
            case "Default" -> {
                setStatusDefault();
            }    
                
            case "Create New Stadium" -> {
                setStatusStadium();
            }
            
            case "Create New Match" -> {
                setStatusMatch();
            }
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBoxSelectActionPerformed

    private void jButtonConfirmStadiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmStadiumActionPerformed
        if (jTextFieldNameStadium.getText().equals("") || jTextFieldLocation.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Stadium s = new Stadium(jTextFieldStadiumID.getText(), 
                jTextFieldNameStadium.getText(), jTextFieldLocation.getText(), Integer.parseInt(jTextFieldCapacity.getText()));
               
        if (DataBaseConnect.insertStadium(s) == true) {
            JOptionPane.showMessageDialog(this, "Thêm sân vận động thành công!", "Information", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        setStatusDefault();
    }//GEN-LAST:event_jButtonConfirmStadiumActionPerformed

    private void jButtonConfirmMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmMatchActionPerformed
        DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime date = null; 
        try {
            date = LocalDateTime.parse(jTextFieldMatchDate.getText(),f);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (jTextFieldHomeTeam.getText().equals("") || jTextFieldAwayTeam.getText().equals("") || jTextFieldTournament.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Match m = new Match(jTextFieldMatchID.getText(), jTextFieldHomeTeam.getText(), 
                jTextFieldAwayTeam.getText(), (String)jComboBoxStadiumId.getSelectedItem(), 
                date, jTextFieldTournament.getText());
        if (DataBaseConnect.insertMatch(m) == true) {
            JOptionPane.showMessageDialog(this, "Thêm Trận đấu thành công!", "Information", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }     
        setStatusDefault();
    }//GEN-LAST:event_jButtonConfirmMatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmMatch;
    private javax.swing.JButton jButtonConfirmStadium;
    private javax.swing.JComboBox<String> jComboBoxSelect;
    private javax.swing.JComboBox<String> jComboBoxStadiumId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAwayTeam;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldHomeTeam;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldMatchDate;
    private javax.swing.JTextField jTextFieldMatchID;
    private javax.swing.JTextField jTextFieldNameStadium;
    private javax.swing.JTextField jTextFieldStadiumID;
    private javax.swing.JTextField jTextFieldTournament;
    // End of variables declaration//GEN-END:variables
}
