package com.tab;

import com.UserInterface;
import com.connectdatabase.DataBaseConnect;
import com.objects.Match;
import com.objects.Order;
import com.objects.Payment;
import com.objects.Seat;
import com.objects.Stadium;
import com.objects.Ticket;
import com.objects.User;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoah
 */
public class TabManager extends javax.swing.JPanel {

    private DefaultTableModel model = new DefaultTableModel();
    private UserInterface userInterface;

    /**
     * Creates new form TabShowTicket1
     *
     * @param userInterface
     */
    public TabManager(UserInterface userInterface) {
        initComponents();
        this.userInterface = userInterface;
        model = (DefaultTableModel) jTableShow.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShow = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSelect = new javax.swing.JComboBox<>();
        jLabelChange = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableShow);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manager48.png"))); // NOI18N
        jLabel1.setText("Manager");

        jComboBoxSelect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Users", "Orders", "Payments", "Tickets", "Seats", "Stadiums", "Matches", "Seat Availability Report", "Top 5 Highest-Spending Customers", "Average Ticket Price Per Tournament", "Rush Hour For Booking", "Ranking Stadium Revenue", "Top 5 Teams by Total Payment Revenue" }));
        jComboBoxSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelChange, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectActionPerformed
        // TODO add your handling code here:
        String entity = (String) jComboBoxSelect.getSelectedItem();
        changeIconLabel(entity);
        switch (entity) {
            case "Users" -> {
                ArrayList<User> listUser = new ArrayList<>();
                listUser = DataBaseConnect.selectListUser();
                String[] column0 = {"User ID", "Full Name", "Email", "Phone", "Password", "Created"};
                model.setColumnIdentifiers(column0);
                model.setRowCount(0);
                for (User u : listUser) {
                    Object[] row = new Object[]{
                        u.getUser_id(),
                        u.getFull_name(),
                        u.getEmail(),
                        u.getPhone(),
                        u.getPass(),
                        u.getDate().toString()
                    };
                    model.addRow(row);
                }
            }

            case "Orders" -> {
                ArrayList<Order> listOrder = new ArrayList<>();
                listOrder = DataBaseConnect.selectListOrder();
                String[] column1 = {"Order ID", "User ID", "Order Date", "Total Amount", "Status"};
                model.setColumnIdentifiers(column1);
                model.setRowCount(0);
                for (Order o : listOrder) {
                    Object[] row = new Object[]{
                        o.getOrder_id(),
                        o.getUser_id(),
                        o.getOrder_date().toString(),
                        o.getTotal_amount(),
                        o.getStatus()
                    };
                    model.addRow(row);
                }
            }

            case "Payments" -> {
                ArrayList<Payment> listPayment = new ArrayList<>();
                listPayment = DataBaseConnect.selectListPayment();
                String[] column2 = {"Order ID", "User ID", "Order Date", "Total Amount", "Status"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                for (Payment p : listPayment) {
                    Object[] row = new Object[]{
                        p.getPayment_id(),
                        p.getOrder_id(),
                        p.getMethod(),
                        p.getAmount(),
                        p.getStatus(),
                        p.getPayment_date().toString()
                    };
                    model.addRow(row);
                }
            }

            case "Matches" -> {
                ArrayList<Match> listMatch = new ArrayList<>();
                listMatch = DataBaseConnect.selectListMatch();
                String[] column3 = {"Match ID", "Home team", "Away team", "Stadium ID", "Match Date", "Tournament"};
                model.setColumnIdentifiers(column3);
                model.setRowCount(0);
                for (Match m : listMatch) {
                    Object[] row = new Object[]{
                        m.getMatch_id(),
                        m.getHome_team(),
                        m.getAway_team(),
                        m.getStadium_id(),
                        m.getMatch_date().toString(),
                        m.getTournament()
                    };
                    model.addRow(row);
                }
            }

            case "Seats" -> {
                ArrayList<Seat> listSeat = new ArrayList<>();
                listSeat = DataBaseConnect.selectListSeat();
                String[] column4 = {"Match ID", "Stadium ID", "Seat ID", "Status"};
                model.setColumnIdentifiers(column4);
                model.setRowCount(0);
                for (Seat s : listSeat) {
                    Object[] row = new Object[]{
                        s.getMatch_id(),
                        s.getStadium_id(),
                        s.getSeat_id(),
                        s.isStatus()
                    };
                    model.addRow(row);
                }
            }

            case "Stadiums" -> {
                ArrayList<Stadium> listStadium = new ArrayList<>();
                listStadium = DataBaseConnect.selectListStadium();
                String[] column5 = {"Stadium ID", "Name", "Location", "Capacity"};
                model.setColumnIdentifiers(column5);
                model.setRowCount(0);
                for (Stadium s : listStadium) {
                    Object[] row = new Object[]{
                        s.getStadium_id(),
                        s.getName(),
                        s.getLocation(),
                        s.getCapacity()
                    };
                    model.addRow(row);
                }
            }

            case "Tickets" -> {
                ArrayList<Ticket> listTicket = new ArrayList<>();
                listTicket = DataBaseConnect.selectListTicket();
                String[] column6 = {"Ticket ID", "Order ID", "Match ID", "Seat ID", "Price"};
                model.setColumnIdentifiers(column6);
                model.setRowCount(0);
                for (Ticket t : listTicket) {
                    Object[] row = new Object[]{
                        t.getTicket_id(),
                        t.getOrder_id(),
                        t.getMatch_id(),
                        t.getSeat_id(),
                        t.getPrice()
                    };
                    model.addRow(row);
                }
            }
            
            case "Seat Availability Report" -> {
                String[] column1 = {"Match ID", "Stadium Name", "Home Team", "Away Team", "Booked Seats", "Available Seats"};
                model.setColumnIdentifiers(column1);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectSeatAvailabilityReport();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        m.get(1),
                        m.get(2),
                        m.get(3),
                        m.get(4),
                        m.get(5)
                    };
                    model.addRow(row);
                }
            }
            
            case "Top 5 Highest-Spending Customers" -> {
                String[] column2 = {"User ID", "Full Name", "Total Revenue"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectTop5HighestSpendingCustomers();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        m.get(1),
                        formatCurrency(m.get(2))
                    };
                    model.addRow(row);
                }
            }
            
            
            case "Average Ticket Price Per Tournament" -> {
                String[] column2 = {"Tournament", "Average Price"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectAverageTicketPricePerTournament();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        formatCurrency(m.get(1))
                    };
                    model.addRow(row);
                }
            }
            
            case "Rush Hour For Booking" -> {
                String[] column2 = {"Frame Time", "Quantity"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectRushHourForBooking();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        m.get(1)
                    };
                    model.addRow(row);
                }
            }
            
            case "Ranking Stadium Revenue" -> {
                String[] column2 = {"Rank", "Stadium", "Total Revenue"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectRankingStadiumRevenue();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        m.get(1),
                        formatCurrency(m.get(2))
                    };
                    model.addRow(row);
                }
            }
            
            case "Top 5 Teams by Total Payment Revenue" -> {
                String[] column2 = {"Team", "Total Revenue"};
                model.setColumnIdentifiers(column2);
                model.setRowCount(0);
                ArrayList <ArrayList<Object>> arr = DataBaseConnect.selectTop5TeamsByTotalPaymentRevenue();
                for (ArrayList<Object> m : arr) {
                    Object[] row = new Object[]{
                        m.get(0),
                        formatCurrency(m.get(1))
                    };
                    model.addRow(row);
                }
            }
            
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBoxSelectActionPerformed

    public static String formatCurrency(Object amount) {
        if (amount == null) return "0";
        try {
            long value = Long.parseLong(amount.toString());        
            NumberFormat formatter = NumberFormat.getNumberInstance(Locale.getDefault());
            return formatter.format(value);
        } catch (NumberFormatException e) {
            return amount.toString();
        }
    }
    
    private void changeIconLabel(String choice) {
        switch (choice) {
            case "Users" -> {
                java.net.URL imgURL = getClass().getResource("/users.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }
            
            case "Orders" -> {
                java.net.URL imgURL = getClass().getResource("/orders.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }
            
            case "Stadiums" -> {
                java.net.URL imgURL = getClass().getResource("/stadiums.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }
            
            case "Matches" -> {
                java.net.URL imgURL = getClass().getResource("/matches.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }
            
            case "Seats" -> {
                java.net.URL imgURL = getClass().getResource("/seats.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }    
            
            case "Tickets" -> {
                java.net.URL imgURL = getClass().getResource("/tickets.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            } 
            
            case "Payments" -> {
                java.net.URL imgURL = getClass().getResource("/payments.png");
                if (imgURL != null) {
                    jLabelChange.setIcon(new ImageIcon(imgURL));
                }
            }
            
            default -> {
                jLabelChange.setIcon(null);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableShow;
    // End of variables declaration//GEN-END:variables
}
