package com.tab;

import com.UserInterface;
import com.connectdatabase.DataBaseConnect;
import com.objects.Order;
import com.objects.Payment;
import com.objects.Seat;
import com.objects.User;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

public class TabOrderAndPayment extends javax.swing.JPanel {

    /**
     * Creates new form TabThanhToan
     */
    private UserInterface userInterface;
    private ArrayList <Seat> listSeat;
    private Order orderCucBo;
    private int price;

    public TabOrderAndPayment(UserInterface userInterface, User user, ArrayList<Seat> seats, int amount, int price) {
        initComponents();
        this.price = price;
        this.userInterface = userInterface;
        this.listSeat = seats;
        initStatusOver();
        initStatusOrder(user, amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonConfirmOrder = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldOrderID = new javax.swing.JTextField();
        jTextFieldUserID = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jTextFieldDateOrder = new javax.swing.JTextField();
        jComboBoxSatusOrder = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPayID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldOrderIDInPay = new javax.swing.JTextField();
        jTextFieldAmountPay = new javax.swing.JTextField();
        jComboxMethodPayment = new javax.swing.JComboBox<>();
        jComboBoxStatusPayment = new javax.swing.JComboBox<>();
        jTextFieldPayDate = new javax.swing.JTextField();
        jButtonPay = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(900, 520));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonConfirmOrder.setBackground(new java.awt.Color(52, 152, 219));
        jButtonConfirmOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConfirmOrder.setText("Confirm");
        jButtonConfirmOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConfirmOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConfirmOrderMouseExited(evt);
            }
        });
        jButtonConfirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmOrderActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 42, 86));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t48icket.png"))); // NOI18N
        jLabel9.setText("ORDER");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("User ID:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Order ID:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Status:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Amount:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Order date:  ");

        jTextFieldOrderID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldOrderID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jTextFieldUserID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUserID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jTextFieldAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jTextFieldDateOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldDateOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jComboBoxSatusOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxSatusOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Paid", "Cancelled" }));
        jComboBoxSatusOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(127, 127, 127))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDateOrder)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonConfirmOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxSatusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOrderID)
                                    .addComponent(jTextFieldAmount)
                                    .addComponent(jTextFieldUserID))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSatusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButtonConfirmOrder)
                .addGap(38, 38, 38))
        );

        add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Payment ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Order ID: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Method:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Amount:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Status:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Payment date:  ");

        jTextFieldPayID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPayID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 42, 86));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Payment_48.png"))); // NOI18N
        jLabel7.setText("PAYMENT");

        jTextFieldOrderIDInPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldOrderIDInPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jTextFieldAmountPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAmountPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jComboxMethodPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboxMethodPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARD", "MOMO", "PAYPAL", "CASH" }));
        jComboxMethodPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jComboBoxStatusPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxStatusPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Success", "Failed" }));
        jComboBoxStatusPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jTextFieldPayDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPayDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));

        jButtonPay.setBackground(new java.awt.Color(46, 204, 113));
        jButtonPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPay.setText("Pay");
        jButtonPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPayMouseExited(evt);
            }
        });
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("VAT 10%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldPayDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(jTextFieldPayID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOrderIDInPay)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboxMethodPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStatusPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAmountPay, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel14))
                            .addComponent(jButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPayID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOrderIDInPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboxMethodPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAmountPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStatusPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButtonPay)
                .addGap(38, 38, 38))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        jButtonPay.setText("Paied");
        jButtonPay.setEnabled(false);
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        Payment p = new Payment(jTextFieldPayID.getText(), jTextFieldOrderIDInPay.getText(), 
                (String) jComboxMethodPayment.getSelectedItem(), Integer.parseInt(jTextFieldAmountPay.getText()), 
                (String) jComboBoxStatusPayment.getSelectedItem(), LocalDateTime.parse(jTextFieldDateOrder.getText()));
        if (DataBaseConnect.insertPayMent(p) > 0) {
            JOptionPane.showMessageDialog(this, "Thanh Toán thành công", "Information", JOptionPane.OK_OPTION);
            jButtonPay.setText("Đã Thanh Toán");
            jButtonPay.setEnabled(false);
            userInterface.deleteTab();
            userInterface.btnPayInTabOrderAndPayment(orderCucBo, listSeat, price);
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi, hãy khởi động lại!", "Erorr", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void jButtonConfirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmOrderActionPerformed
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        orderCucBo = new Order(
                jTextFieldOrderID.getText(),
                jTextFieldUserID.getText(),
                LocalDateTime.parse(jTextFieldDateOrder.getText()),
                Integer.parseInt(jTextFieldAmount.getText()),
                (String) jComboBoxSatusOrder.getSelectedItem()
        );
        
        if (DataBaseConnect.insertOrder(orderCucBo) > 0) {
            JOptionPane.showMessageDialog(this, "Xác nhận thành công", "Information", JOptionPane.OK_OPTION);
            jButtonConfirmOrder.setEnabled(false);
            jButtonConfirmOrder.setText("Confirmed");
            jButtonPay.setEnabled(true);
            initPayment();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi, hãy khởi động lại!", "Erorr", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfirmOrderActionPerformed

    private void jButtonConfirmOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmOrderMouseEntered
        java.awt.Color XACNHAN_DEFAULT = new java.awt.Color(41, 128, 185);
        jButtonConfirmOrder.setBackground(XACNHAN_DEFAULT);
    }//GEN-LAST:event_jButtonConfirmOrderMouseEntered

    private void jButtonConfirmOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmOrderMouseExited
        java.awt.Color XACNHAN_DEFAULT = new java.awt.Color(52, 152, 219);
        jButtonConfirmOrder.setBackground(XACNHAN_DEFAULT);
    }//GEN-LAST:event_jButtonConfirmOrderMouseExited

    private void jButtonPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPayMouseEntered
        java.awt.Color THANHTOAN_HOVER = new java.awt.Color(39, 174, 96);
        jButtonPay.setBackground(THANHTOAN_HOVER);
    }//GEN-LAST:event_jButtonPayMouseEntered

    private void jButtonPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPayMouseExited
        java.awt.Color THANHTOAN_DEFAULT = new java.awt.Color(46, 204, 113);
        jButtonConfirmOrder.setBackground(THANHTOAN_DEFAULT);
    }//GEN-LAST:event_jButtonPayMouseExited

    private void initPayment() {
        LocalDateTime time = LocalDateTime.now();
        //DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
        //String stime = time.format(f);
        int amountPay = (int) (Integer.parseInt(jTextFieldAmount.getText()) * 1.1);
        jTextFieldPayID.setText(createPayID());
        jTextFieldOrderIDInPay.setText(jTextFieldOrderID.getText());
        jTextFieldAmountPay.setText("" + amountPay);
        jTextFieldPayDate.setText(time.toString());
    }

    private void initStatusOver() {
        jTextFieldUserID.setEditable(false);
        jTextFieldDateOrder.setEditable(false);
        jTextFieldAmount.setEditable(false);
        jTextFieldOrderID.setEditable(false);
        jButtonPay.setEnabled(false);
        jTextFieldPayID.setEditable(false);
        jTextFieldOrderIDInPay.setEditable(false);
        jTextFieldAmountPay.setEditable(false);
        jTextFieldPayDate.setEditable(false);
    }

    private void initStatusOrder(User user, int amount) {
        LocalDateTime time = LocalDateTime.now();
        //DateTimeFormatter f = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm:ss");
        //String stime = time.format(f);
        jTextFieldOrderID.setText(createOrderID());
        jTextFieldUserID.setText(user.getUser_id());
        jTextFieldAmount.setText("" + amount);
        jTextFieldDateOrder.setText(time.toString());
    }

    private String createOrderID() {
        String prefix = "ORD";
        Random rand = new Random();
        StringBuilder sb = new StringBuilder(prefix);

        for (int i = 0; i < 7; i++) {
            int so = rand.nextInt(10); 
            sb.append(so);
        }

        return sb.toString();
    }
    
    private String createPayID() {
        String prefix = "PID";
        Random rand = new Random();
        StringBuilder sb = new StringBuilder(prefix);

        for (int i = 0; i < 7; i++) {
            int so = rand.nextInt(10); 
            sb.append(so);
        }

        return sb.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmOrder;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JComboBox<String> jComboBoxSatusOrder;
    private javax.swing.JComboBox<String> jComboBoxStatusPayment;
    private javax.swing.JComboBox<String> jComboxMethodPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldAmountPay;
    private javax.swing.JTextField jTextFieldDateOrder;
    private javax.swing.JTextField jTextFieldOrderID;
    private javax.swing.JTextField jTextFieldOrderIDInPay;
    private javax.swing.JTextField jTextFieldPayDate;
    private javax.swing.JTextField jTextFieldPayID;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
