package com.tab;

import com.UserInterface;
import com.connectdatabase.DataBaseConnect;
import com.objects.Order;
import com.objects.Seat;
import com.objects.Ticket;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoah
 */
public class TabShowTicket extends javax.swing.JPanel {

    private DefaultTableModel model = new DefaultTableModel();
    private ArrayList <Ticket> listTicket = new ArrayList<>();
    private UserInterface userInterface;
    private int price = 0;
    /**
     * Creates new form TabShowTicket1
     * @param userInterface
     * @param order
     * @param listSeat
     */
    
    public TabShowTicket(UserInterface userInterface ,Order order, ArrayList <Seat> listSeat, int gia) {
        initComponents();
        this.userInterface = userInterface;
        this.price = gia;
        model = (DefaultTableModel) jTableShow.getModel();
        initData(order, listSeat);
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShow = new javax.swing.JTable();
        jButtonConfirm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ticket ID", "Order ID", "Match ID", "Seat ID", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableShow);

        jButtonConfirm.setBackground(new java.awt.Color(25, 114, 210));
        jButtonConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t48icket.png"))); // NOI18N
        jLabel1.setText("Ticket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConfirm)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        model.setRowCount(0);
        for (Ticket t : listTicket) {
            Object[] row = new Object[]{
                t.getTicket_id(),
                t.getOrder_id(),
                t.getMatch_id(),
                t.getSeat_id(),
                t.getPrice()
            };
            model.addRow(row);
        }
    }
    
    
    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        for (Ticket t : listTicket) {
            DataBaseConnect.intertTicket(t);
        }
        jButtonConfirm.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Thành Công", "Inforamtion", JOptionPane.OK_OPTION);
        userInterface.deleteTab();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void initData(Order o, ArrayList <Seat> list) {
        for (Seat s : list) {
            Ticket t = new Ticket(createIDTicket(), o.getOrder_id(), s.getMatch_id(), s.getSeat_id(), price);
            listTicket.add(t);
        }
    }
    
    private String createIDTicket() {
        String prefix = "TIC";
        Random rand = new Random();
        StringBuilder sb = new StringBuilder(prefix);

        for (int i = 0; i < 7; i++) {
            int so = rand.nextInt(10);
            sb.append(so);
        }

        return sb.toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableShow;
    // End of variables declaration//GEN-END:variables
}
