
package com;

import com.connectdatabase.DataBaseConnect;
import com.dialog.JDialogAboutUs;
import com.dialog.jDialogRegister;
import com.dialog.jDialogUserOld;
import com.objects.Order;
import com.objects.Seat;
import com.objects.User;
import com.tab.TabBookSeat;
import com.tab.TabManager;
import com.tab.TabCreateNew;
import com.tab.TabOrderAndPayment;
import com.tab.TabShowTicket;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class UserInterface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserInterface.class.getName());
    int weightMenuBar = 200;
    int heightMenuBar = 558;
    boolean checkOpenMenuBar = false;
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        setTitle("FootBall");
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(this);
        setSize(1010, 640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TabMain = new javax.swing.JTabbedPane();
        TpnBoard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonBookTicket1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBookTicket2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonBookTicket3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonBookTicket4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelOpenAndCloseMenuBar = new javax.swing.JLabel();
        jLabelToCloseThisTab = new javax.swing.JLabel();
        MenuAnimation = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelMenuBarExit = new javax.swing.JLabel();
        jLabelMenuAboutUs = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabelUserOld = new javax.swing.JLabel();
        jLabelManager = new javax.swing.JLabel();
        jLabelResetData = new javax.swing.JLabel();
        jLabelCreateNew = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 66, 66));

        TabMain.setPreferredSize(new java.awt.Dimension(1000, 500));

        TpnBoard.setBackground(new java.awt.Color(255, 255, 255));
        TpnBoard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TpnBoard.setPreferredSize(new java.awt.Dimension(1200, 463));
        TpnBoard.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(100, 181, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(230, 451));

        jButtonBookTicket1.setBackground(new java.awt.Color(25, 118, 210));
        jButtonBookTicket1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonBookTicket1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookTicket1.setText("BUY TICKET");
        jButtonBookTicket1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBookTicket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookTicket1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Match No. 1");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thailand.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vietnam.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("V/S");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VIE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THA");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Monday");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBookTicket1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBookTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 185;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        TpnBoard.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(100, 181, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(188, 450));

        jButtonBookTicket2.setBackground(new java.awt.Color(25, 118, 210));
        jButtonBookTicket2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonBookTicket2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookTicket2.setText("BUY TICKET");
        jButtonBookTicket2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBookTicket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookTicket2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Match No. 2");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("V/S");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uruguay.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/England.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ENG");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("URU");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Thurday");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBookTicket2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBookTicket2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 0);
        TpnBoard.add(jPanel2, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(100, 181, 246));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(188, 450));

        jButtonBookTicket3.setBackground(new java.awt.Color(25, 118, 210));
        jButtonBookTicket3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonBookTicket3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookTicket3.setText("BUY TICKET");
        jButtonBookTicket3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBookTicket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookTicket3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Match No. 3");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("V/S");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Germany.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Brazil.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BRA");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("GER");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Sunday");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBookTicket3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBookTicket3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 0);
        TpnBoard.add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(100, 181, 246));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(188, 450));

        jButtonBookTicket4.setBackground(new java.awt.Color(25, 118, 210));
        jButtonBookTicket4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonBookTicket4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookTicket4.setText("BUY TICKET");
        jButtonBookTicket4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBookTicket4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookTicket4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Match No. 4");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("V/S");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Portugal.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Japan.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("JPN");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("POR");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Tuesday");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBookTicket4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel28)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jButtonBookTicket4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 6, 6);
        TpnBoard.add(jPanel6, gridBagConstraints);

        TabMain.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/home24.png")), TpnBoard); // NOI18N

        jLabelOpenAndCloseMenuBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu32.png"))); // NOI18N
        jLabelOpenAndCloseMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpenAndCloseMenuBarMouseClicked(evt);
            }
        });

        jLabelToCloseThisTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close 32.png"))); // NOI18N
        jLabelToCloseThisTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToCloseThisTabMouseClicked(evt);
            }
        });

        MenuAnimation.setBackground(new java.awt.Color(26, 32, 38));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foot94.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conf24.png"))); // NOI18N
        jLabel32.setText("Features");

        jLabelMenuBarExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMenuBarExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuBarExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit24.png"))); // NOI18N
        jLabelMenuBarExit.setText("Exit");
        jLabelMenuBarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuBarExitMouseClicked(evt);
            }
        });

        jLabelMenuAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMenuAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info24.png"))); // NOI18N
        jLabelMenuAboutUs.setText("Introduce");
        jLabelMenuAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuAboutUsMouseClicked(evt);
            }
        });

        jLabel29.setText("________________________________________");

        jLabel33.setText("________________________________________");

        jLabelUserOld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUserOld.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/khangia24.png"))); // NOI18N
        jLabelUserOld.setText("Registered Audience");
        jLabelUserOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserOldMouseClicked(evt);
            }
        });

        jLabelManager.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelManager.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanly24.png"))); // NOI18N
        jLabelManager.setText("For Management");
        jLabelManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManagerMouseClicked(evt);
            }
        });

        jLabelResetData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelResetData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResetData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting24.png"))); // NOI18N
        jLabelResetData.setText("Reset Data");
        jLabelResetData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetDataMouseClicked(evt);
            }
        });

        jLabelCreateNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCreateNew.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCreateNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/create24.png"))); // NOI18N
        jLabelCreateNew.setText("Create Stadium Match");
        jLabelCreateNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateNewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuAnimationLayout = new javax.swing.GroupLayout(MenuAnimation);
        MenuAnimation.setLayout(MenuAnimationLayout);
        MenuAnimationLayout.setHorizontalGroup(
            MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuAnimationLayout.createSequentialGroup()
                        .addGroup(MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MenuAnimationLayout.createSequentialGroup()
                                .addComponent(jLabelMenuAboutUs)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuAnimationLayout.createSequentialGroup()
                        .addGroup(MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelMenuBarExit)
                                .addComponent(jLabelUserOld)
                                .addComponent(jLabelManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31)
                                .addComponent(jLabelResetData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel32))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelCreateNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MenuAnimationLayout.setVerticalGroup(
            MenuAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(44, 44, 44)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserOld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResetData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabelMenuAboutUs)
                .addGap(18, 18, 18)
                .addComponent(jLabelMenuBarExit)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOpenAndCloseMenuBar)
                .addGap(18, 18, 18)
                .addComponent(jLabelToCloseThisTab)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOpenAndCloseMenuBar)
                    .addComponent(jLabelToCloseThisTab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToCloseThisTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToCloseThisTabMouseClicked
        int index = TabMain.getSelectedIndex();
        String title = TabMain.getTitleAt(index);
        boolean check = false;
        
        if (title.equals("Book Seat") || title.equals("Confirm and Payment") || title.equals("Ticket")) {
            check = true;
        }
        if (index != 0 && check == false) {
            TabMain.remove(index);
        }
    }//GEN-LAST:event_jLabelToCloseThisTabMouseClicked

    public void deleteTab() {
        int index = TabMain.getSelectedIndex();
        if (index != 0) {
            TabMain.remove(index);
        }
    }
    
    public void deleteTabByComponent(Component component) {
        int index = TabMain.indexOfComponent(component);
        if (index != -1) {
            TabMain.remove(index);
        }
    }

    
    private void jLabelOpenAndCloseMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpenAndCloseMenuBarMouseClicked
        if (!checkOpenMenuBar) {
            openMenuBar();
            TabMain.setVisible(false);
            checkOpenMenuBar = true;
            changIconForOpenAndCloseMenuBar(jLabelOpenAndCloseMenuBar, "/left32.png");
        } else {
            closeMenuBar();
            TabMain.setVisible(true);
            checkOpenMenuBar = false;
            changIconForOpenAndCloseMenuBar(jLabelOpenAndCloseMenuBar, "/menu32.png");
        }
    }//GEN-LAST:event_jLabelOpenAndCloseMenuBarMouseClicked

    private void jLabelMenuAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuAboutUsMouseClicked
        JDialogAboutUs aboutus = new JDialogAboutUs(this, true);
        aboutus.setVisible(true);
    }//GEN-LAST:event_jLabelMenuAboutUsMouseClicked

    private void jLabelMenuBarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuBarExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelMenuBarExitMouseClicked

    private void jButtonBookTicket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookTicket1ActionPerformed
        jDialogRegister dialog = new jDialogRegister(this, true);
        dialog.setVisible(true);
        User registeredUser = dialog.getU();
        if (registeredUser == null || dialog.isClose() == true) {
            return;
        }
        TabBookSeat tab = new TabBookSeat(this, registeredUser);
        TabMain.addTab("Book Seat", tab);
        TabMain.setSelectedComponent(tab);
        if (tab.test() == true) {
            JOptionPane.showMessageDialog(this, "Không có trận đấu nào!");
            deleteTab();
        }
    }//GEN-LAST:event_jButtonBookTicket1ActionPerformed

    private void jLabelManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManagerMouseClicked
        TabManager tab = new TabManager(this);
        TabMain.add("Manager", tab);
        TabMain.setSelectedComponent(tab);
        jLabelOpenAndCloseMenuBarMouseClicked(evt);
    }//GEN-LAST:event_jLabelManagerMouseClicked

    private void jButtonBookTicket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookTicket2ActionPerformed
        jButtonBookTicket1ActionPerformed(evt);
    }//GEN-LAST:event_jButtonBookTicket2ActionPerformed

    private void jButtonBookTicket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookTicket3ActionPerformed
        jButtonBookTicket1ActionPerformed(evt);
    }//GEN-LAST:event_jButtonBookTicket3ActionPerformed

    private void jButtonBookTicket4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookTicket4ActionPerformed
        jButtonBookTicket1ActionPerformed(evt);
    }//GEN-LAST:event_jButtonBookTicket4ActionPerformed

    private void jLabelUserOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserOldMouseClicked
        jDialogUserOld dialog = new jDialogUserOld(this, true);
        dialog.setVisible(true);
        User registeredUser = dialog.getU();
        if (registeredUser == null || dialog.isClose() == true) {
            return;
        }
        TabBookSeat tab = new TabBookSeat(this, registeredUser);
        TabMain.addTab("Book Seat", tab);
        TabMain.setSelectedComponent(tab);
        jLabelOpenAndCloseMenuBarMouseClicked(evt);
    }//GEN-LAST:event_jLabelUserOldMouseClicked

    private void jLabelResetDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetDataMouseClicked
        try {
            if (DataBaseConnect.resetAllData() == 1) {
                JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công", "Inforamtion", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(this, "Thất Bại", "Inforamtion", JOptionPane.OK_OPTION);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            System.getLogger(UserInterface.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        jLabelOpenAndCloseMenuBarMouseClicked(evt);
    }//GEN-LAST:event_jLabelResetDataMouseClicked

    private void jLabelCreateNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateNewMouseClicked
        TabCreateNew tab = new TabCreateNew(this);
        TabMain.add("New", tab);
        TabMain.setSelectedComponent(tab);
        jLabelOpenAndCloseMenuBarMouseClicked(evt);
    }//GEN-LAST:event_jLabelCreateNewMouseClicked
    
    void openMenuBar () {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= weightMenuBar; ++i) {
                    MenuAnimation.setSize(i, heightMenuBar);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        System.getLogger(UserInterface.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        }).start();
    }
    
    void closeMenuBar () {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = weightMenuBar; i >= 0; --i) {
                    MenuAnimation.setSize(i, heightMenuBar);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        System.getLogger(UserInterface.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }               
            }
        }).start();
    }
    
    private void changIconForOpenAndCloseMenuBar(JLabel label, String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            label.setIcon(new ImageIcon(imgURL));
        } else {
            System.err.println("Không tìm thấy icon: " + path);
        }
    }
    
    public void btnBookTicketInTabBookTicKet(User user, ArrayList <Seat> seats, int amount) {
        TabOrderAndPayment tab = new TabOrderAndPayment(this, user, seats, amount);
        TabMain.addTab("Confirm and Payment", tab);
        TabMain.setSelectedComponent(tab);
    }
    
    public void btnPayInTabOrderAndPayment(Order order, ArrayList <Seat> listSeat) {
        TabShowTicket tab = new TabShowTicket(this ,order, listSeat);
        TabMain.addTab("Ticket", tab);
        TabMain.setSelectedComponent(tab);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserInterface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuAnimation;
    private javax.swing.JTabbedPane TabMain;
    private javax.swing.JPanel TpnBoard;
    private javax.swing.JButton jButtonBookTicket1;
    private javax.swing.JButton jButtonBookTicket2;
    private javax.swing.JButton jButtonBookTicket3;
    private javax.swing.JButton jButtonBookTicket4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreateNew;
    private javax.swing.JLabel jLabelManager;
    private javax.swing.JLabel jLabelMenuAboutUs;
    private javax.swing.JLabel jLabelMenuBarExit;
    private javax.swing.JLabel jLabelOpenAndCloseMenuBar;
    private javax.swing.JLabel jLabelResetData;
    private javax.swing.JLabel jLabelToCloseThisTab;
    private javax.swing.JLabel jLabelUserOld;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
