
package com.tab;

import com.UserInterface;
import com.connectdatabase.DataBaseConnect;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TabBookTicket extends javax.swing.JPanel {
    /**
     * Creates new form TabBookTicket
     * @param userInterface
     */
    
    
    public ArrayList <String> gheDuocDat = new ArrayList<>();
    private static int soLuong = 0;
    private final int donGia = 40000;
    
    public TabBookTicket(UserInterface userInterface){
        initComponents();
        setMatchIDTojcbxSelectMatch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatPanel = new javax.swing.JPanel();
        gheA01 = new javax.swing.JButton();
        gheA02 = new javax.swing.JButton();
        gheA03 = new javax.swing.JButton();
        gheA04 = new javax.swing.JButton();
        gheA05 = new javax.swing.JButton();
        gheA06 = new javax.swing.JButton();
        gheA07 = new javax.swing.JButton();
        gheA08 = new javax.swing.JButton();
        gheA09 = new javax.swing.JButton();
        gheA10 = new javax.swing.JButton();
        gheB01 = new javax.swing.JButton();
        gheB02 = new javax.swing.JButton();
        gheB03 = new javax.swing.JButton();
        gheB04 = new javax.swing.JButton();
        gheB05 = new javax.swing.JButton();
        gheB06 = new javax.swing.JButton();
        gheB07 = new javax.swing.JButton();
        gheB08 = new javax.swing.JButton();
        gheB09 = new javax.swing.JButton();
        gheB10 = new javax.swing.JButton();
        gheC01 = new javax.swing.JButton();
        gheC02 = new javax.swing.JButton();
        gheC03 = new javax.swing.JButton();
        gheC04 = new javax.swing.JButton();
        gheC05 = new javax.swing.JButton();
        gheC06 = new javax.swing.JButton();
        gheC07 = new javax.swing.JButton();
        gheC08 = new javax.swing.JButton();
        gheC09 = new javax.swing.JButton();
        gheC10 = new javax.swing.JButton();
        gheD01 = new javax.swing.JButton();
        gheD02 = new javax.swing.JButton();
        gheD03 = new javax.swing.JButton();
        gheD04 = new javax.swing.JButton();
        gheD05 = new javax.swing.JButton();
        gheD06 = new javax.swing.JButton();
        gheD07 = new javax.swing.JButton();
        gheD08 = new javax.swing.JButton();
        gheD09 = new javax.swing.JButton();
        gheD10 = new javax.swing.JButton();
        gheE01 = new javax.swing.JButton();
        gheE02 = new javax.swing.JButton();
        gheE03 = new javax.swing.JButton();
        gheE04 = new javax.swing.JButton();
        gheE05 = new javax.swing.JButton();
        gheE06 = new javax.swing.JButton();
        gheE07 = new javax.swing.JButton();
        gheE08 = new javax.swing.JButton();
        gheE09 = new javax.swing.JButton();
        gheE10 = new javax.swing.JButton();
        gheF01 = new javax.swing.JButton();
        gheF02 = new javax.swing.JButton();
        gheF03 = new javax.swing.JButton();
        gheF04 = new javax.swing.JButton();
        gheF05 = new javax.swing.JButton();
        gheF06 = new javax.swing.JButton();
        gheF07 = new javax.swing.JButton();
        gheF08 = new javax.swing.JButton();
        gheF09 = new javax.swing.JButton();
        gheF10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSeat = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jcbxSelectMatch = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(900, 520));

        seatPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gheA01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA01.setText("A01");
        gheA01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA01.setPreferredSize(new java.awt.Dimension(25, 25));
        gheA01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gheA01ActionPerformed(evt);
            }
        });

        gheA02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA02.setText("A02");
        gheA02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA02.setPreferredSize(new java.awt.Dimension(25, 25));
        gheA02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gheA02ActionPerformed(evt);
            }
        });

        gheA03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA03.setText("A03");
        gheA03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA04.setText("A04");
        gheA04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA05.setText("A05");
        gheA05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA06.setText("A06");
        gheA06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA07.setText("A07");
        gheA07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA08.setText("A08");
        gheA08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA09.setText("A09");
        gheA09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheA10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheA10.setText("A10");
        gheA10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheA10.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB01.setText("B01");
        gheB01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB01.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB02.setText("B02");
        gheB02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB02.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB03.setText("B03");
        gheB03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB04.setText("B04");
        gheB04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB05.setText("B05");
        gheB05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB06.setText("B06");
        gheB06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB07.setText("B07");
        gheB07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB08.setText("B08");
        gheB08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB09.setText("B09");
        gheB09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheB10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheB10.setText("B10");
        gheB10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheB10.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC01.setText("C01");
        gheC01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC01.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC02.setText("C02");
        gheC02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC02.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC03.setText("C03");
        gheC03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC04.setText("C04");
        gheC04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC05.setText("C05");
        gheC05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC06.setText("C06");
        gheC06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC07.setText("C07");
        gheC07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC08.setText("C08");
        gheC08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC09.setText("C09");
        gheC09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheC10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheC10.setText("C10");
        gheC10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheC10.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD01.setText("D01");
        gheD01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD01.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD02.setText("D02");
        gheD02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD02.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD03.setText("D03");
        gheD03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD04.setText("D04");
        gheD04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD05.setText("D05");
        gheD05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD06.setText("D06");
        gheD06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD07.setText("D07");
        gheD07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD08.setText("D08");
        gheD08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD09.setText("D09");
        gheD09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheD10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheD10.setText("D10");
        gheD10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheD10.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE01.setText("E01");
        gheE01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE01.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE02.setText("E02");
        gheE02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE02.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE03.setText("E03");
        gheE03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE04.setText("E04");
        gheE04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE05.setText("E05");
        gheE05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE06.setText("E06");
        gheE06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE07.setText("E07");
        gheE07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE08.setText("E08");
        gheE08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE09.setText("E09");
        gheE09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheE10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheE10.setText("E10");
        gheE10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheE10.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF01.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF01.setText("F01");
        gheF01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF01.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF02.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF02.setText("F02");
        gheF02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF02.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF03.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF03.setText("F03");
        gheF03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF03.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF04.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF04.setText("F04");
        gheF04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF04.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF05.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF05.setText("F05");
        gheF05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF05.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF06.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF06.setText("F06");
        gheF06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF06.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF07.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF07.setText("F07");
        gheF07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF07.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF08.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF08.setText("F08");
        gheF08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF08.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF09.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF09.setText("F09");
        gheF09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF09.setPreferredSize(new java.awt.Dimension(25, 25));

        gheF10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gheF10.setText("F10");
        gheF10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gheF10.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addComponent(gheB01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheB10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addComponent(gheA01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheA10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gheE01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gheD01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(gheE02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(gheD02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(gheE04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheE10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addComponent(gheF01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheF10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addComponent(gheC01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheC02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheC03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(gheC04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gheC05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(gheD06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheD10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(gheC06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheC07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheC08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheC09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gheC10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheA01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA06, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA07, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA08, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA09, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheA10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheB01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB06, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB07, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB08, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB09, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheB10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheC01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC06, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC07, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC08, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC09, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheC10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheD05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD06, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD07, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD08, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD09, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheD04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheE01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE06, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE07, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE08, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE09, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheE10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gheF01, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF02, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF03, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF04, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF05, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF06, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF07, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF08, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF09, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gheF10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("User ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Phone: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PassWord:");

        jTextField1.setText("10002321");

        jTextField2.setText("Huỳnh Hoàng Khoa");

        jTextField3.setText("N23DCCN166");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("0375065207");

        jPasswordField1.setText("jPasswordField1");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Đặt Vé");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Seat:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Amount:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1)
                            .addComponent(txtSeat)
                            .addComponent(txtAmount))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jcbxSelectMatch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbxSelectMatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Match1 (VIE - THA)", "Match2 (ENG - URU)", "Match3 (BRA - GER)", "Match4 (JPN - POR)" }));
        jcbxSelectMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxSelectMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbxSelectMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbxSelectMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setMatchIDTojcbxSelectMatch() {
        ArrayList<String> data = DataBaseConnect.getMatchID();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String item : data) {
            model.addElement(item);
        }

        jcbxSelectMatch.setModel(model);

        if (!data.isEmpty()) {
            jcbxSelectMatch.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Không có MatchID nào!");
        }
    }
    
    private void jcbxSelectMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSelectMatchActionPerformed
        // TODO add your handling code here:
        String matchID = jcbxSelectMatch.getSelectedItem().toString();
        try {
            ArrayList <Vector> arr = DataBaseConnect.getDataSeatsAccordingToTheMatch(matchID);
            setStatusGheFollowComboBox(arr);
        } catch (SQLException | ClassNotFoundException ex) {
            System.getLogger(TabBookTicket.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
            
    }//GEN-LAST:event_jcbxSelectMatchActionPerformed

    private void setStatusGheFollowComboBox(ArrayList<Vector> arr) {
        for (Vector row : arr) {
            String seatId = row.get(2).toString().trim();  
            int statusInt = (Integer) row.get(3);
            boolean status = (statusInt == 1);  
            
            switch (seatId) {
                case "A01" -> gheA01.setEnabled(!status);
                case "A02" -> gheA02.setEnabled(!status);
                case "A03" -> gheA03.setEnabled(!status);
                case "A04" -> gheA04.setEnabled(!status);
                case "A05" -> gheA05.setEnabled(!status);
                case "A06" -> gheA06.setEnabled(!status);
                case "A07" -> gheA07.setEnabled(!status);
                case "A08" -> gheA08.setEnabled(!status);
                case "A09" -> gheA09.setEnabled(!status);
                case "A10" -> gheA10.setEnabled(!status);
                case "B01" -> gheB01.setEnabled(!status);
                case "B02" -> gheB02.setEnabled(!status);
                case "B03" -> gheB03.setEnabled(!status);
                case "B04" -> gheB04.setEnabled(!status);
                case "B05" -> gheB05.setEnabled(!status);
                case "B06" -> gheB06.setEnabled(!status);
                case "B07" -> gheB07.setEnabled(!status);
                case "B08" -> gheB08.setEnabled(!status);
                case "B09" -> gheB09.setEnabled(!status);
                case "B10" -> gheB10.setEnabled(!status);
                case "C01" -> gheC01.setEnabled(!status);
                case "C02" -> gheC02.setEnabled(!status);
                case "C03" -> gheC03.setEnabled(!status);
                case "C04" -> gheC04.setEnabled(!status);
                case "C05" -> gheC05.setEnabled(!status);
                case "C06" -> gheC06.setEnabled(!status);
                case "C07" -> gheC07.setEnabled(!status);
                case "C08" -> gheC08.setEnabled(!status);
                case "C09" -> gheC09.setEnabled(!status);
                case "C10" -> gheC10.setEnabled(!status);
                case "D01" -> gheD01.setEnabled(!status);
                case "D02" -> gheD02.setEnabled(!status);
                case "D03" -> gheD03.setEnabled(!status);
                case "D04" -> gheD04.setEnabled(!status);
                case "D05" -> gheD05.setEnabled(!status);
                case "D06" -> gheD06.setEnabled(!status);
                case "D07" -> gheD07.setEnabled(!status);
                case "D08" -> gheD08.setEnabled(!status);
                case "D09" -> gheD09.setEnabled(!status);
                case "D10" -> gheD10.setEnabled(!status);
                case "E01" -> gheE01.setEnabled(!status);
                case "E02" -> gheE02.setEnabled(!status);
                case "E03" -> gheE03.setEnabled(!status);
                case "E04" -> gheE04.setEnabled(!status);
                case "E05" -> gheE05.setEnabled(!status);
                case "E06" -> gheE06.setEnabled(!status);
                case "E07" -> gheE07.setEnabled(!status);
                case "E08" -> gheE08.setEnabled(!status);
                case "E09" -> gheE09.setEnabled(!status);
                case "E10" -> gheE10.setEnabled(!status);
                case "F01" -> gheF01.setEnabled(!status);
                case "F02" -> gheF02.setEnabled(!status);
                case "F03" -> gheF03.setEnabled(!status);
                case "F04" -> gheF04.setEnabled(!status);
                case "F05" -> gheF05.setEnabled(!status);
                case "F06" -> gheF06.setEnabled(!status);
                case "F07" -> gheF07.setEnabled(!status);
                case "F08" -> gheF08.setEnabled(!status);
                case "F09" -> gheF09.setEnabled(!status);
                case "F10" -> gheF10.setEnabled(!status);
                default -> {
                }
            }
        }
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void setAmountAndSetAndGheDuocDat(String ghe) {
        gheDuocDat.add(ghe);
        String currentText = txtSeat.getText();
        currentText = currentText + "" + ghe;
        txtSeat.setText(currentText);
        soLuong++;
        txtAmount.setText ("" + soLuong*donGia);
    }
    
    private void gheA01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gheA01ActionPerformed
        // TODO add your handling code here:
        
        gheA01.setBackground(Color.red);
        gheA01.setEnabled(false);
        setAmountAndSetAndGheDuocDat("A01");
        
    }//GEN-LAST:event_gheA01ActionPerformed

    private void gheA02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gheA02ActionPerformed
        // TODO add your handling code here:     
        gheA02.setEnabled(false);
        setAmountAndSetAndGheDuocDat("A02");
        gheA02.setBackground(Color.RED);
        gheA02.setOpaque(true);
        gheA02.setContentAreaFilled(true);
        gheA02.setBorderPainted(true);
        jcbxSelectMatch.setEnabled(false);
    }//GEN-LAST:event_gheA02ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gheA01;
    private javax.swing.JButton gheA02;
    private javax.swing.JButton gheA03;
    private javax.swing.JButton gheA04;
    private javax.swing.JButton gheA05;
    private javax.swing.JButton gheA06;
    private javax.swing.JButton gheA07;
    private javax.swing.JButton gheA08;
    private javax.swing.JButton gheA09;
    private javax.swing.JButton gheA10;
    private javax.swing.JButton gheB01;
    private javax.swing.JButton gheB02;
    private javax.swing.JButton gheB03;
    private javax.swing.JButton gheB04;
    private javax.swing.JButton gheB05;
    private javax.swing.JButton gheB06;
    private javax.swing.JButton gheB07;
    private javax.swing.JButton gheB08;
    private javax.swing.JButton gheB09;
    private javax.swing.JButton gheB10;
    private javax.swing.JButton gheC01;
    private javax.swing.JButton gheC02;
    private javax.swing.JButton gheC03;
    private javax.swing.JButton gheC04;
    private javax.swing.JButton gheC05;
    private javax.swing.JButton gheC06;
    private javax.swing.JButton gheC07;
    private javax.swing.JButton gheC08;
    private javax.swing.JButton gheC09;
    private javax.swing.JButton gheC10;
    private javax.swing.JButton gheD01;
    private javax.swing.JButton gheD02;
    private javax.swing.JButton gheD03;
    private javax.swing.JButton gheD04;
    private javax.swing.JButton gheD05;
    private javax.swing.JButton gheD06;
    private javax.swing.JButton gheD07;
    private javax.swing.JButton gheD08;
    private javax.swing.JButton gheD09;
    private javax.swing.JButton gheD10;
    private javax.swing.JButton gheE01;
    private javax.swing.JButton gheE02;
    private javax.swing.JButton gheE03;
    private javax.swing.JButton gheE04;
    private javax.swing.JButton gheE05;
    private javax.swing.JButton gheE06;
    private javax.swing.JButton gheE07;
    private javax.swing.JButton gheE08;
    private javax.swing.JButton gheE09;
    private javax.swing.JButton gheE10;
    private javax.swing.JButton gheF01;
    private javax.swing.JButton gheF02;
    private javax.swing.JButton gheF03;
    private javax.swing.JButton gheF04;
    private javax.swing.JButton gheF05;
    private javax.swing.JButton gheF06;
    private javax.swing.JButton gheF07;
    private javax.swing.JButton gheF08;
    private javax.swing.JButton gheF09;
    private javax.swing.JButton gheF10;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> jcbxSelectMatch;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtSeat;
    // End of variables declaration//GEN-END:variables
}
